//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridGames.ResX {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GridGames.ResX.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        internal static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a dark theme.
        /// </summary>
        internal static string AppSettingsDarkTheme {
            get {
                return ResourceManager.GetString("AppSettingsDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the theme will restart the current game..
        /// </summary>
        internal static string AppSettingsDarkThemeInstructions {
            get {
                return ResourceManager.GetString("AppSettingsDarkThemeInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Grid.
        /// </summary>
        internal static string AppSettingsHideGrid {
            get {
                return ResourceManager.GetString("AppSettingsHideGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the grid contents are visually hidden, use a screen reader to play the game..
        /// </summary>
        internal static string AppSettingsHideGridInstructions {
            get {
                return ResourceManager.GetString("AppSettingsHideGridInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings here apply to all games in the Grid Games app..
        /// </summary>
        internal static string AppSettingsIntro {
            get {
                return ResourceManager.GetString("AppSettingsIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for picture.
        /// </summary>
        internal static string BrowsePicture {
            get {
                return ResourceManager.GetString("BrowsePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a picture in a folder that contains exactly 8 pictures..
        /// </summary>
        internal static string ChooseEightPictures {
            get {
                return ResourceManager.GetString("ChooseEightPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selection.
        /// </summary>
        internal static string ClearSelection {
            get {
                return ResourceManager.GetString("ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You completed {0} in {1} goes..
        /// </summary>
        internal static string CompletedSquaresPictureInMoves {
            get {
                return ResourceManager.GetString("CompletedSquaresPictureInMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        internal static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A smiling man with a red coat and arms outstretched, standing in front of 3 large Daleks and a TARDIS. The Daleks seem to be raised above the grass beneath them, and a slightly cloudy sky is in the background..
        /// </summary>
        internal static string DefaultMatchingCard1Description {
            get {
                return ResourceManager.GetString("DefaultMatchingCard1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daleks in Blackpool.
        /// </summary>
        internal static string DefaultMatchingCard1Name {
            get {
                return ResourceManager.GetString("DefaultMatchingCard1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A small brown stone lighthouse, with an upper small balcony and a lower bigger balcony. A covered sitting area is at the base of the lighthouse. In front of the lighthouse in the stone ground are anchor and compass symbols, and in the background is a grey cloudy sky..
        /// </summary>
        internal static string DefaultMatchingCard2Description {
            get {
                return ResourceManager.GetString("DefaultMatchingCard2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Lighthouse in Fleetwood.
        /// </summary>
        internal static string DefaultMatchingCard2Name {
            get {
                return ResourceManager.GetString("DefaultMatchingCard2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A first-person view looking down on two portions of fish and chips in trays and paper. In the background is a concrete path, and two partially shown shoes..
        /// </summary>
        internal static string DefaultMatchingCard3Description {
            get {
                return ResourceManager.GetString("DefaultMatchingCard3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish and Chips in Cleveleys.
        /// </summary>
        internal static string DefaultMatchingCard3Name {
            get {
                return ResourceManager.GetString("DefaultMatchingCard3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A small, very old hexagonal red stone building, with castellated battlements housing a cross. Arched windows on the sides of the building are bricked-up from the inside. The building sits on grass, with a bay and cloudy sky in the background..
        /// </summary>
        internal static string DefaultMatchingCard4Description {
            get {
                return ResourceManager.GetString("DefaultMatchingCard4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cockersand Abbey.
        /// </summary>
        internal static string DefaultMatchingCard4Name {
            get {
                return ResourceManager.GetString("DefaultMatchingCard4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A white windmill with a black roof and black sails. The windmill has stairs going up to a black door, and black windows. In the background is a street of houses and a clear, blue sky..
        /// </summary>
        internal static string DefaultMatchingCard5Description {
            get {
                return ResourceManager.GetString("DefaultMatchingCard5Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lytham St Annes Windmill.
        /// </summary>
        internal static string DefaultMatchingCard5Name {
            get {
                return ResourceManager.GetString("DefaultMatchingCard5Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stone ruins of a large, very old abbey. The abbey has no roof or windows, and the sun shines through the arches from behind the abbey. In the foreground is a lawn housing multiple large stone graves, and in the background is a clear blue sky..
        /// </summary>
        internal static string DefaultMatchingCard6Description {
            get {
                return ResourceManager.GetString("DefaultMatchingCard6Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolton Abbey.
        /// </summary>
        internal static string DefaultMatchingCard6Name {
            get {
                return ResourceManager.GetString("DefaultMatchingCard6Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A large stone obelisk in a town square, with buildings and trees nearby. The sun shines on the obelisk, with a slightly cloudy, blue sky in the background. At the base of the obelisk are six red wreaths..
        /// </summary>
        internal static string DefaultMatchingCard7Description {
            get {
                return ResourceManager.GetString("DefaultMatchingCard7Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harrogate Obelisk.
        /// </summary>
        internal static string DefaultMatchingCard7Name {
            get {
                return ResourceManager.GetString("DefaultMatchingCard7Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A small square stone building with an opening on the near side. Above the opening is a Greek inscription. Railing surrounds the top of the building, and a sundial sits at the centre of the top. In the background is rocky grassland, with rolling hills in the far background along with a slightly cloudy, blue sky..
        /// </summary>
        internal static string DefaultMatchingCard8Description {
            get {
                return ResourceManager.GetString("DefaultMatchingCard8Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hampsfell Hospice.
        /// </summary>
        internal static string DefaultMatchingCard8Name {
            get {
                return ResourceManager.GetString("DefaultMatchingCard8Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string DefaultSquare10Name {
            get {
                return ResourceManager.GetString("DefaultSquare10Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string DefaultSquare11Name {
            get {
                return ResourceManager.GetString("DefaultSquare11Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string DefaultSquare12Name {
            get {
                return ResourceManager.GetString("DefaultSquare12Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string DefaultSquare13Name {
            get {
                return ResourceManager.GetString("DefaultSquare13Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string DefaultSquare14Name {
            get {
                return ResourceManager.GetString("DefaultSquare14Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string DefaultSquare15Name {
            get {
                return ResourceManager.GetString("DefaultSquare15Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string DefaultSquare1Name {
            get {
                return ResourceManager.GetString("DefaultSquare1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string DefaultSquare2Name {
            get {
                return ResourceManager.GetString("DefaultSquare2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string DefaultSquare3Name {
            get {
                return ResourceManager.GetString("DefaultSquare3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string DefaultSquare4Name {
            get {
                return ResourceManager.GetString("DefaultSquare4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string DefaultSquare5Name {
            get {
                return ResourceManager.GetString("DefaultSquare5Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string DefaultSquare6Name {
            get {
                return ResourceManager.GetString("DefaultSquare6Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string DefaultSquare7Name {
            get {
                return ResourceManager.GetString("DefaultSquare7Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string DefaultSquare8Name {
            get {
                return ResourceManager.GetString("DefaultSquare8Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string DefaultSquare9Name {
            get {
                return ResourceManager.GetString("DefaultSquare9Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string DefaultSquareEmpty {
            get {
                return ResourceManager.GetString("DefaultSquareEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to down.
        /// </summary>
        internal static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eight.
        /// </summary>
        internal static string Eight {
            get {
                return ResourceManager.GetString("Eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eleven.
        /// </summary>
        internal static string Eleven {
            get {
                return ResourceManager.GetString("Eleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face down.
        /// </summary>
        internal static string FaceDown {
            get {
                return ResourceManager.GetString("FaceDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifteen.
        /// </summary>
        internal static string Fifteen {
            get {
                return ResourceManager.GetString("Fifteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill card and clip.
        /// </summary>
        internal static string FillCardAndClip {
            get {
                return ResourceManager.GetString("FillCardAndClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill card without clipping.
        /// </summary>
        internal static string FillCardWithoutClipping {
            get {
                return ResourceManager.GetString("FillCardWithoutClipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five.
        /// </summary>
        internal static string Five {
            get {
                return ResourceManager.GetString("Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four.
        /// </summary>
        internal static string Four {
            get {
                return ResourceManager.GetString("Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourteen.
        /// </summary>
        internal static string Fourteen {
            get {
                return ResourceManager.GetString("Fourteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game is ready to play..
        /// </summary>
        internal static string GameReady {
            get {
                return ResourceManager.GetString("GameReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Games.
        /// </summary>
        internal static string GridGames {
            get {
                return ResourceManager.GetString("GridGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pairs Game is based on a traditional card matching game, where face-down cards are turned over in order to find pairs of cards.
        ///
        ///When the game is run, a 4 by 4 grid of blank squares appears, each square representing a card. When a card is tapped, an image is shown on the card. When another card is clicked, an image is also shown on that second card. If the two images are the same, then the cards are considered to be matched, and will not change again for the rest of the game. If the images do not matc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpContentPairs {
            get {
                return ResourceManager.GetString("HelpContentPairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Squares Game is based on a square sliding puzzle, where squares in a grid of squares are rearranged by the player to form an ordered sequence in the grid.
        ///
        ///When the game is run, a 4 by 4 grid of squares appears, with fifteen of those squares occupied with a movable element, and one square being empty. When a square is tapped, if it is adjacent to the empty square, the tapped square moves into the empty square. The space where the tapped square was then becomes the empty square. The aim is to arrange a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpContentSquares {
            get {
                return ResourceManager.GetString("HelpContentSquares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        internal static string Large {
            get {
                return ResourceManager.GetString("Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largest.
        /// </summary>
        internal static string Largest {
            get {
                return ResourceManager.GetString("Largest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded custom pictures.
        /// </summary>
        internal static string LoadedCustomPictures {
            get {
                return ResourceManager.GetString("LoadedCustomPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait a moment while the picture is loaded into the squares..
        /// </summary>
        internal static string LoadingPleaseWait {
            get {
                return ResourceManager.GetString("LoadingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched.
        /// </summary>
        internal static string Matched {
            get {
                return ResourceManager.GetString("Matched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won the game in {0} goes..
        /// </summary>
        internal static string MatchingWonInMoves {
            get {
                return ResourceManager.GetString("MatchingWonInMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder containing the 8 picture must also contain a MatchingGamePictureDetails file. Please review the Pairs Help for more details..
        /// </summary>
        internal static string MissingMatchingGamePictureDetails {
            get {
                return ResourceManager.GetString("MissingMatchingGamePictureDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved.
        /// </summary>
        internal static string Moved {
            get {
                return ResourceManager.GetString("Moved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine.
        /// </summary>
        internal static string Nine {
            get {
                return ResourceManager.GetString("Nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No folder selected.
        /// </summary>
        internal static string NoFolderSelected {
            get {
                return ResourceManager.GetString("NoFolderSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A move is not possible from here..
        /// </summary>
        internal static string NoMovePossible {
            get {
                return ResourceManager.GetString("NoMovePossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number size.
        /// </summary>
        internal static string NumberSize {
            get {
                return ResourceManager.GetString("NumberSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One.
        /// </summary>
        internal static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairs.
        /// </summary>
        internal static string Pairs {
            get {
                return ResourceManager.GetString("Pairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairs Help.
        /// </summary>
        internal static string PairsGameHelp {
            get {
                return ResourceManager.GetString("PairsGameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairs Settings.
        /// </summary>
        internal static string PairsSettings {
            get {
                return ResourceManager.GetString("PairsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Pairs Game!.
        /// </summary>
        internal static string PairsWelcome {
            get {
                return ResourceManager.GetString("PairsWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick how the pictures will be shown in the cards..
        /// </summary>
        internal static string PictureAspectInstructions {
            get {
                return ResourceManager.GetString("PictureAspectInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale type.
        /// </summary>
        internal static string PictureAspectLabel {
            get {
                return ResourceManager.GetString("PictureAspectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture Name:.
        /// </summary>
        internal static string PictureNameLabel {
            get {
                return ResourceManager.GetString("PictureNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture Path:.
        /// </summary>
        internal static string PicturePath {
            get {
                return ResourceManager.GetString("PicturePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play a sound when upturned cards match.
        /// </summary>
        internal static string PlaySoundMatch {
            get {
                return ResourceManager.GetString("PlaySoundMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play a sound when upturned cards don&apos;t match.
        /// </summary>
        internal static string PlaySoundNotMatch {
            get {
                return ResourceManager.GetString("PlaySoundNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Game.
        /// </summary>
        internal static string RestartGame {
            get {
                return ResourceManager.GetString("RestartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected:.
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Picture.
        /// </summary>
        internal static string SelectPicture {
            get {
                return ResourceManager.GetString("SelectPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven.
        /// </summary>
        internal static string Seven {
            get {
                return ResourceManager.GetString("Seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show custom pictures.
        /// </summary>
        internal static string ShowCustomPictures {
            get {
                return ResourceManager.GetString("ShowCustomPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show full picture.
        /// </summary>
        internal static string ShowFullPicture {
            get {
                return ResourceManager.GetString("ShowFullPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show numbers.
        /// </summary>
        internal static string ShowNumbers {
            get {
                return ResourceManager.GetString("ShowNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show picture.
        /// </summary>
        internal static string ShowPicture {
            get {
                return ResourceManager.GetString("ShowPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Six.
        /// </summary>
        internal static string Six {
            get {
                return ResourceManager.GetString("Six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sixteen.
        /// </summary>
        internal static string Sixteen {
            get {
                return ResourceManager.GetString("Sixteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        internal static string Small {
            get {
                return ResourceManager.GetString("Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squares.
        /// </summary>
        internal static string Squares {
            get {
                return ResourceManager.GetString("Squares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squares Help.
        /// </summary>
        internal static string SquaresGameHelp {
            get {
                return ResourceManager.GetString("SquaresGameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squares Settings.
        /// </summary>
        internal static string SquaresSettings {
            get {
                return ResourceManager.GetString("SquaresSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify what you would like to appear inside the squares shown in the grid..
        /// </summary>
        internal static string SquaresSettingsInstructions {
            get {
                return ResourceManager.GetString("SquaresSettingsInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Squares Game!.
        /// </summary>
        internal static string SquaresWelcome {
            get {
                return ResourceManager.GetString("SquaresWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won the game in {0} moves..
        /// </summary>
        internal static string SquaresWonInGoes {
            get {
                return ResourceManager.GetString("SquaresWonInGoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to play another game?.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the game is run, a 4 by 4 grid of blank squares appears, each square representing a card. When a card is tapped, an image is shown on the card. When another card is clicked, an image is also shown on that second card. If the two images are the same, then the cards are considered to be matched, and will not change again for the rest of the game. If the images do not match, then the cards are considered to be unmatched, and cards must be turned back over by tapping on any card. These steps are to be repe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the game setting to have a picture shown on the squares is on, then a single picture is shown across all the squares. The sections of the picture will appear jumbled until the squares are arranged in their sorted order..
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using a screen reader with the game, move your finger around the screen to have the number of the square beneath your finger announced. Double tap to move a square..
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note when a screen reader moves to the Menu button near the top left corner of the app, it may announce the button as the OK button or Menu button, or only announce the word button..
        /// </summary>
        internal static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to play another game?.
        /// </summary>
        internal static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to play another game?.
        /// </summary>
        internal static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note that screen readers may announce the menu button as the &quot;OK&quot; button or only as &quot;button&quot;..
        /// </summary>
        internal static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using a screen reader with the game, move your finger around the screen to have the number of the card beneath your finger announced. Double tap to turn up a card. When a turned up card is matched, its name will be prefixed with &quot;Matched&quot;..
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note when a screen reader moves to the Menu button near the top left corner of the app, it may announce the button as the OK button or Menu button, or only announce the word button..
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Squares Game is based on a square sliding puzzle, where squares in a grid of squares are rearranged by the player to form an ordered sequence in the grid..
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the game is run, a 4 by 4 grid of squares appears, with fifteen of those squares occupied with a movable element, and one square being empty. When a square is tapped, if it is adjacent to the empty square, the tapped square moves into the empty square. The space where the tapped square was then becomes the empty square. The aim is to arrange all the squares in a sorted order, leaving the empty square in the bottom right corner of the grid. Once all the squares are ordered, a &quot;Congratulations&quot; window ap [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: Don&apos;t use a swipe gesture to move a square. Support for swipe gestures has yet to be added to the game..
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: Don&apos;t tap on the empty square. Instead tap on the squares next to the empty square..
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the game first runs, the setting to have numbers shown on squares is on, and the settings to have pictures shown on the squares is off. This means a number is shown in the top left corner of the squares. When the squares are sorted, the square showing number 1 is at the top left of the grid, and the numbers increase from left to right then top to bottom..
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: Practice moving numbered squares around before changing the setting to have a picture shown on the squares..
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten.
        /// </summary>
        internal static string Ten {
            get {
                return ResourceManager.GetString("Ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s a match..
        /// </summary>
        internal static string ThatsMatch {
            get {
                return ResourceManager.GetString("ThatsMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thirteen.
        /// </summary>
        internal static string Thirteen {
            get {
                return ResourceManager.GetString("Thirteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three.
        /// </summary>
        internal static string Three {
            get {
                return ResourceManager.GetString("Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turned up.
        /// </summary>
        internal static string TurnedUp {
            get {
                return ResourceManager.GetString("TurnedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twelve.
        /// </summary>
        internal static string Twelve {
            get {
                return ResourceManager.GetString("Twelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two.
        /// </summary>
        internal static string Two {
            get {
                return ResourceManager.GetString("Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MatchingGamePictureDetails file does not contain the expected data. Please review the Pairs Help for more details..
        /// </summary>
        internal static string UnexpectedDataInFile {
            get {
                return ResourceManager.GetString("UnexpectedDataInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmatched cards turned back..
        /// </summary>
        internal static string UnmatchedTurnedBack {
            get {
                return ResourceManager.GetString("UnmatchedTurnedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to up.
        /// </summary>
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After closing this message, please review the help content in the menu for details on how to play this game..
        /// </summary>
        internal static string WelcomeInstructions {
            get {
                return ResourceManager.GetString("WelcomeInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
