//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridGames.ResX {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GridGames.ResX.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        internal static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a dark theme.
        /// </summary>
        internal static string AppSettingsDarkTheme {
            get {
                return ResourceManager.GetString("AppSettingsDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the theme will restart the current game..
        /// </summary>
        internal static string AppSettingsDarkThemeInstructions {
            get {
                return ResourceManager.GetString("AppSettingsDarkThemeInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings here apply to all games in the Grid Games app..
        /// </summary>
        internal static string AppSettingsIntro {
            get {
                return ResourceManager.GetString("AppSettingsIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check one or more WCAG before submitting your answer. Groups of WCAG will be shown after making selections at the WCAG group pickers..
        /// </summary>
        internal static string BonusAnswerRequired {
            get {
                return ResourceManager.GetString("BonusAnswerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for picture.
        /// </summary>
        internal static string BrowsePicture {
            get {
                return ResourceManager.GetString("BrowsePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        internal static string CellLocalizedControlType {
            get {
                return ResourceManager.GetString("CellLocalizedControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a picture in a folder that contains exactly 8 pictures..
        /// </summary>
        internal static string ChooseEightPictures {
            get {
                return ResourceManager.GetString("ChooseEightPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selection.
        /// </summary>
        internal static string ClearSelection {
            get {
                return ResourceManager.GetString("ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You completed {0} in {1} goes.
        ///
        ///Would you like to play another game?.
        /// </summary>
        internal static string CompletedSquaresPictureInMoves {
            get {
                return ResourceManager.GetString("CompletedSquaresPictureInMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You helped all the frogs!
        ///
        ///Would you like to play another game?.
        /// </summary>
        internal static string CompletedSweeper {
            get {
                return ResourceManager.GetString("CompletedSweeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        internal static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You found {0}. Now where&apos;s {1}?.
        /// </summary>
        internal static string CorrectWCAG {
            get {
                return ResourceManager.GetString("CorrectWCAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To prepare custom pictures for showing in the Pairs game, first create a new folder and copy in the eight pictures that you&apos;d like to have shown. Then create a text file in the same folder, called &quot;PairsGamePictureDetails.txt&quot;. Edit the text file so that each line in the file contains the accessible details for one of the pictures in the folder. A line starts with the filename of the picture, followed by a tab, and then the accessible name of the picture. If a description is also provided, the name is follo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CustomPicturesInstructions {
            get {
                return ResourceManager.GetString("CustomPicturesInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A smiling man with a red coat and arms outstretched, standing in front of 3 large Daleks and a TARDIS. The Daleks seem to be raised above the grass beneath them, and a slightly cloudy sky is in the background..
        /// </summary>
        internal static string DefaultMatchingCard1Description {
            get {
                return ResourceManager.GetString("DefaultMatchingCard1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daleks in Blackpool.
        /// </summary>
        internal static string DefaultMatchingCard1Name {
            get {
                return ResourceManager.GetString("DefaultMatchingCard1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A small brown stone lighthouse, with an upper small balcony and a lower bigger balcony. A covered sitting area is at the base of the lighthouse. In front of the lighthouse in the stone ground are anchor and compass symbols, and in the background is a grey cloudy sky..
        /// </summary>
        internal static string DefaultMatchingCard2Description {
            get {
                return ResourceManager.GetString("DefaultMatchingCard2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Lighthouse in Fleetwood.
        /// </summary>
        internal static string DefaultMatchingCard2Name {
            get {
                return ResourceManager.GetString("DefaultMatchingCard2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A first-person view looking down on two portions of fish and chips in trays and paper. In the background is a concrete path, and two partially shown shoes..
        /// </summary>
        internal static string DefaultMatchingCard3Description {
            get {
                return ResourceManager.GetString("DefaultMatchingCard3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish and Chips in Cleveleys.
        /// </summary>
        internal static string DefaultMatchingCard3Name {
            get {
                return ResourceManager.GetString("DefaultMatchingCard3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A small, very old hexagonal red stone building, with castellated battlements housing a cross. Arched windows on the sides of the building are bricked-up from the inside. The building sits on grass, with a bay and cloudy sky in the background..
        /// </summary>
        internal static string DefaultMatchingCard4Description {
            get {
                return ResourceManager.GetString("DefaultMatchingCard4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cockersand Abbey.
        /// </summary>
        internal static string DefaultMatchingCard4Name {
            get {
                return ResourceManager.GetString("DefaultMatchingCard4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A white windmill with a black roof and black sails. The windmill has stairs going up to a black door, and black windows. In the background is a street of houses and a clear, blue sky..
        /// </summary>
        internal static string DefaultMatchingCard5Description {
            get {
                return ResourceManager.GetString("DefaultMatchingCard5Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lytham St Annes Windmill.
        /// </summary>
        internal static string DefaultMatchingCard5Name {
            get {
                return ResourceManager.GetString("DefaultMatchingCard5Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stone ruins of a large, very old abbey. The abbey has no roof or windows, and the sun shines through the arches from behind the abbey. In the foreground is a lawn housing multiple large stone graves, and in the background is a clear blue sky..
        /// </summary>
        internal static string DefaultMatchingCard6Description {
            get {
                return ResourceManager.GetString("DefaultMatchingCard6Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolton Abbey.
        /// </summary>
        internal static string DefaultMatchingCard6Name {
            get {
                return ResourceManager.GetString("DefaultMatchingCard6Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A large stone obelisk in a town square, with buildings and trees nearby. The sun shines on the obelisk, with a slightly cloudy, blue sky in the background. At the base of the obelisk are six red wreaths..
        /// </summary>
        internal static string DefaultMatchingCard7Description {
            get {
                return ResourceManager.GetString("DefaultMatchingCard7Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harrogate Obelisk.
        /// </summary>
        internal static string DefaultMatchingCard7Name {
            get {
                return ResourceManager.GetString("DefaultMatchingCard7Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A small square stone building with an opening on the near side. Above the opening is a Greek inscription. Railing surrounds the top of the building, and a sundial sits at the centre of the top. In the background is rocky grassland, with rolling hills in the far background along with a slightly cloudy, blue sky..
        /// </summary>
        internal static string DefaultMatchingCard8Description {
            get {
                return ResourceManager.GetString("DefaultMatchingCard8Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hampsfell Hospice.
        /// </summary>
        internal static string DefaultMatchingCard8Name {
            get {
                return ResourceManager.GetString("DefaultMatchingCard8Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string DefaultSquare10Name {
            get {
                return ResourceManager.GetString("DefaultSquare10Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string DefaultSquare11Name {
            get {
                return ResourceManager.GetString("DefaultSquare11Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string DefaultSquare12Name {
            get {
                return ResourceManager.GetString("DefaultSquare12Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string DefaultSquare13Name {
            get {
                return ResourceManager.GetString("DefaultSquare13Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string DefaultSquare14Name {
            get {
                return ResourceManager.GetString("DefaultSquare14Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string DefaultSquare15Name {
            get {
                return ResourceManager.GetString("DefaultSquare15Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string DefaultSquare1Name {
            get {
                return ResourceManager.GetString("DefaultSquare1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string DefaultSquare2Name {
            get {
                return ResourceManager.GetString("DefaultSquare2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string DefaultSquare3Name {
            get {
                return ResourceManager.GetString("DefaultSquare3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string DefaultSquare4Name {
            get {
                return ResourceManager.GetString("DefaultSquare4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string DefaultSquare5Name {
            get {
                return ResourceManager.GetString("DefaultSquare5Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string DefaultSquare6Name {
            get {
                return ResourceManager.GetString("DefaultSquare6Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string DefaultSquare7Name {
            get {
                return ResourceManager.GetString("DefaultSquare7Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string DefaultSquare8Name {
            get {
                return ResourceManager.GetString("DefaultSquare8Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string DefaultSquare9Name {
            get {
                return ResourceManager.GetString("DefaultSquare9Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string DefaultSquareEmpty {
            get {
                return ResourceManager.GetString("DefaultSquareEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to down.
        /// </summary>
        internal static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eight.
        /// </summary>
        internal static string Eight {
            get {
                return ResourceManager.GetString("Eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eleven.
        /// </summary>
        internal static string Eleven {
            get {
                return ResourceManager.GetString("Eleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face down.
        /// </summary>
        internal static string FaceDown {
            get {
                return ResourceManager.GetString("FaceDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice try, but a resting frog got swept up with the leaves!
        ///
        ///Would you like to play another game?.
        /// </summary>
        internal static string FailedSweeper {
            get {
                return ResourceManager.GetString("FailedSweeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the keyboard to play the game.
        ///
        ///Review the Help content for details on how to play the game using only the keyboard..
        /// </summary>
        internal static string FallthroughTapMessage {
            get {
                return ResourceManager.GetString("FallthroughTapMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fifteen.
        /// </summary>
        internal static string Fifteen {
            get {
                return ResourceManager.GetString("Fifteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill card and clip.
        /// </summary>
        internal static string FillCardAndClip {
            get {
                return ResourceManager.GetString("FillCardAndClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill card without clipping.
        /// </summary>
        internal static string FillCardWithoutClipping {
            get {
                return ResourceManager.GetString("FillCardWithoutClipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to five.
        /// </summary>
        internal static string Five {
            get {
                return ResourceManager.GetString("Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to four.
        /// </summary>
        internal static string Four {
            get {
                return ResourceManager.GetString("Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourteen.
        /// </summary>
        internal static string Fourteen {
            get {
                return ResourceManager.GetString("Fourteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frog.
        /// </summary>
        internal static string Frog {
            get {
                return ResourceManager.GetString("Frog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game is ready to play..
        /// </summary>
        internal static string GameReady {
            get {
                return ResourceManager.GetString("GameReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a tip.
        /// </summary>
        internal static string GetTip {
            get {
                return ResourceManager.GetString("GetTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Games.
        /// </summary>
        internal static string GridGames {
            get {
                return ResourceManager.GetString("GridGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        internal static string GridLocalizedControlType {
            get {
                return ResourceManager.GetString("GridLocalizedControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pairs Game is based on a traditional card matching game, where face-down cards are turned over in order to find pairs of cards.
        ///
        ///When the game is run, a 4 by 4 grid of blank squares appears, each square representing a face-down card. When one of the cards is turned up, it reveals an image on the face-up card. When another card is turned up, an image is also shown on that second face-up card. If the two images are the same, then the cards are considered to be matched, and will not change again for the  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpContentPairs {
            get {
                return ResourceManager.GetString("HelpContentPairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Squares Game is based on a square sliding puzzle, where squares in a grid of squares are rearranged by the player to form an ordered sequence of squares in the grid.
        ///
        ///When the game is run, a 4 by 4 grid of squares appears, with fifteen of those squares occupied with a movable element, and one square being empty. When a square is clicked, if it is adjacent to the empty square, the clicked square moves into the empty square. The space where the tapped square was then becomes the empty square. The aim is [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpContentSquares {
            get {
                return ResourceManager.GetString("HelpContentSquares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Leaf Sweeper Game is based on the traditional Minesweeper game, but the aim of this game is to sweep the leaves off a group of paving stones without disturbing two frogs resting under the leaves on two of the stones.
        ///
        ///When the game is run, a 4-by-4 grid of squares appears, with each square showing a leaf symbol. The squares represent a group of paving stones covered with leaves. First clear the leaves off one of the stones by clicking on the stone. When using a keyboard, move focus to the grid of squa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpContentSweeper {
            get {
                return ResourceManager.GetString("HelpContentSweeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;WCAG&quot; is the Web Content Accessibility Guidelines (WCAG) international standard, which helps web content authors create content that&apos;s more accessible. The WCAG standard has been used as the base for European accessibility standards which apply to both web content and software.
        ///
        ///The Where&apos;s WCAG? game presents a question asking the player to find a particular WCAG group. For example, &quot;Where&apos;s Enough Time?&quot;. Below the question in the app is a 4 by 4 grid of squares showing fifteen WCAG group numbers. For  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpContentWheres {
            get {
                return ResourceManager.GetString("HelpContentWheres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} isn&apos;t {1}..
        /// </summary>
        internal static string IncorrectWCAG {
            get {
                return ResourceManager.GetString("IncorrectWCAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        internal static string Large {
            get {
                return ResourceManager.GetString("Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largest.
        /// </summary>
        internal static string Largest {
            get {
                return ResourceManager.GetString("Largest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaf.
        /// </summary>
        internal static string Leaf {
            get {
                return ResourceManager.GetString("Leaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded custom pictures.
        /// </summary>
        internal static string LoadedCustomPictures {
            get {
                return ResourceManager.GetString("LoadedCustomPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait a moment while the picture is loaded into the squares..
        /// </summary>
        internal static string LoadingPleaseWait {
            get {
                return ResourceManager.GetString("LoadingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched.
        /// </summary>
        internal static string Matched {
            get {
                return ResourceManager.GetString("Matched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won the game in {0} goes.
        ///
        ///Would you like to play another game?.
        /// </summary>
        internal static string MatchingWonInMoves {
            get {
                return ResourceManager.GetString("MatchingWonInMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder containing the 8 picture must also contain a PairsGamePictureDetails file. Please review the Pairs Help for more details..
        /// </summary>
        internal static string MissingPairsGamePictureDetails {
            get {
                return ResourceManager.GetString("MissingPairsGamePictureDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved.
        /// </summary>
        internal static string Moved {
            get {
                return ResourceManager.GetString("Moved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nine.
        /// </summary>
        internal static string Nine {
            get {
                return ResourceManager.GetString("Nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No folder selected.
        /// </summary>
        internal static string NoFolderSelected {
            get {
                return ResourceManager.GetString("NoFolderSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A move is not possible from here..
        /// </summary>
        internal static string NoMovePossible {
            get {
                return ResourceManager.GetString("NoMovePossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number size.
        /// </summary>
        internal static string NumberSize {
            get {
                return ResourceManager.GetString("NumberSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one.
        /// </summary>
        internal static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!.
        /// </summary>
        internal static string Oops {
            get {
                return ResourceManager.GetString("Oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairs.
        /// </summary>
        internal static string Pairs {
            get {
                return ResourceManager.GetString("Pairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sample custom pictures folder is available at https://github.com/gbarkerz/GridGames/tree/master/GridGames/PairsSamples/LittleMoretonHall. Consider making your own set of pictures and accessible details, and showing in the Pairs game..
        /// </summary>
        internal static string PairsCustomPicturesViewSample {
            get {
                return ResourceManager.GetString("PairsCustomPicturesViewSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairs Help.
        /// </summary>
        internal static string PairsGameHelp {
            get {
                return ResourceManager.GetString("PairsGameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairs Settings.
        /// </summary>
        internal static string PairsSettings {
            get {
                return ResourceManager.GetString("PairsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Pairs Game!.
        /// </summary>
        internal static string PairsWelcome {
            get {
                return ResourceManager.GetString("PairsWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick how the pictures will be shown in the cards..
        /// </summary>
        internal static string PictureAspectInstructions {
            get {
                return ResourceManager.GetString("PictureAspectInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale type.
        /// </summary>
        internal static string PictureAspectLabel {
            get {
                return ResourceManager.GetString("PictureAspectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture Name:.
        /// </summary>
        internal static string PictureNameLabel {
            get {
                return ResourceManager.GetString("PictureNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected picture folder:.
        /// </summary>
        internal static string PicturePath {
            get {
                return ResourceManager.GetString("PicturePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query frog.
        /// </summary>
        internal static string QueryFrog {
            get {
                return ResourceManager.GetString("QueryFrog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Game.
        /// </summary>
        internal static string RestartGame {
            get {
                return ResourceManager.GetString("RestartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        internal static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected:.
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select picture folder.
        /// </summary>
        internal static string SelectPicture {
            get {
                return ResourceManager.GetString("SelectPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To select the picture folder, browse to the folder of interest and select any file in that folder..
        /// </summary>
        internal static string SelectPictureFolderInstructionsFileInFolder {
            get {
                return ResourceManager.GetString("SelectPictureFolderInstructionsFileInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To select the pictures and their descriptions, browse to the folder of interest and select the eight picture files and the PairsGamePictureDetails.txt file..
        /// </summary>
        internal static string SelectPictureFolderInstructionsFiles {
            get {
                return ResourceManager.GetString("SelectPictureFolderInstructionsFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To select the picture folder, browse to the folder of interest and select it..
        /// </summary>
        internal static string SelectPictureFolderInstructionsFolder {
            get {
                return ResourceManager.GetString("SelectPictureFolderInstructionsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seven.
        /// </summary>
        internal static string Seven {
            get {
                return ResourceManager.GetString("Seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show bonus WCAG questions.
        /// </summary>
        internal static string ShowBonusQuestion {
            get {
                return ResourceManager.GetString("ShowBonusQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show custom pictures.
        /// </summary>
        internal static string ShowCustomPictures {
            get {
                return ResourceManager.GetString("ShowCustomPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show full picture.
        /// </summary>
        internal static string ShowFullPicture {
            get {
                return ResourceManager.GetString("ShowFullPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show numbers.
        /// </summary>
        internal static string ShowNumbers {
            get {
                return ResourceManager.GetString("ShowNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show picture.
        /// </summary>
        internal static string ShowPicture {
            get {
                return ResourceManager.GetString("ShowPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to six.
        /// </summary>
        internal static string Six {
            get {
                return ResourceManager.GetString("Six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sixteen.
        /// </summary>
        internal static string Sixteen {
            get {
                return ResourceManager.GetString("Sixteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        internal static string Small {
            get {
                return ResourceManager.GetString("Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squares.
        /// </summary>
        internal static string Squares {
            get {
                return ResourceManager.GetString("Squares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squares Help.
        /// </summary>
        internal static string SquaresGameHelp {
            get {
                return ResourceManager.GetString("SquaresGameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squares Settings.
        /// </summary>
        internal static string SquaresSettings {
            get {
                return ResourceManager.GetString("SquaresSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify what you would like to appear inside the squares shown in the grid..
        /// </summary>
        internal static string SquaresSettingsInstructions {
            get {
                return ResourceManager.GetString("SquaresSettingsInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Squares Game!.
        /// </summary>
        internal static string SquaresWelcome {
            get {
                return ResourceManager.GetString("SquaresWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won the game in {0} moves.
        ///
        ///Would you like to play another game?.
        /// </summary>
        internal static string SquaresWonInGoes {
            get {
                return ResourceManager.GetString("SquaresWonInGoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to play another game?.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the game is run, a 4 by 4 grid of blank squares appears, each square representing a card. When a card is tapped, an image is shown on the card. When another card is clicked, an image is also shown on that second card. If the two images are the same, then the cards are considered to be matched, and will not change again for the rest of the game. If the images do not match, then the cards are considered to be unmatched, and cards must be turned back over by tapping on any card. These steps are to be repe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the game setting to have a picture shown on the squares is on, then a single picture is shown across all the squares. The sections of the picture will appear jumbled until the squares are arranged in their sorted order..
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using a screen reader with the game, move your finger around the screen to have the number of the square beneath your finger announced. Double tap to move a square..
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note when a screen reader moves to the Menu button near the top left corner of the app, it may announce the button as the OK button or Menu button, or only announce the word button..
        /// </summary>
        internal static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to play another game?.
        /// </summary>
        internal static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to play another game?.
        /// </summary>
        internal static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note that screen readers may announce the menu button as the &quot;OK&quot; button or only as &quot;button&quot;..
        /// </summary>
        internal static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using a screen reader with the game, move your finger around the screen to have the number of the card beneath your finger announced. Double tap to turn up a card. When a turned up card is matched, its name will be prefixed with &quot;Matched&quot;..
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note when a screen reader moves to the Menu button near the top left corner of the app, it may announce the button as the OK button or Menu button, or only announce the word button..
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Squares Game is based on a square sliding puzzle, where squares in a grid of squares are rearranged by the player to form an ordered sequence in the grid..
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the game is run, a 4 by 4 grid of squares appears, with fifteen of those squares occupied with a movable element, and one square being empty. When a square is tapped, if it is adjacent to the empty square, the tapped square moves into the empty square. The space where the tapped square was then becomes the empty square. The aim is to arrange all the squares in a sorted order, leaving the empty square in the bottom right corner of the grid. Once all the squares are ordered, a &quot;Congratulations&quot; window ap [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: Don&apos;t use a swipe gesture to move a square. Support for swipe gestures has yet to be added to the game..
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: Don&apos;t tap on the empty square. Instead tap on the squares next to the empty square..
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the game first runs, the setting to have numbers shown on squares is on, and the settings to have pictures shown on the squares is off. This means a number is shown in the top left corner of the squares. When the squares are sorted, the square showing number 1 is at the top left of the grid, and the numbers increase from left to right then top to bottom..
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: Practice moving numbered squares around before changing the setting to have a picture shown on the squares..
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku.
        /// </summary>
        internal static string Sudoku {
            get {
                return ResourceManager.GetString("Sudoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sudoku game is ready to play!.
        /// </summary>
        internal static string SudokuReadyToPlay {
            get {
                return ResourceManager.GetString("SudokuReadyToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku Settings.
        /// </summary>
        internal static string SudokuSettings {
            get {
                return ResourceManager.GetString("SudokuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudoku Squares.
        /// </summary>
        internal static string SudokuSquares {
            get {
                return ResourceManager.GetString("SudokuSquares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Sudoku Game!.
        /// </summary>
        internal static string SudokuWelcome {
            get {
                return ResourceManager.GetString("SudokuWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaf Sweeper.
        /// </summary>
        internal static string Sweeper {
            get {
                return ResourceManager.GetString("Sweeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweeper Settings.
        /// </summary>
        internal static string SweeperSettings {
            get {
                return ResourceManager.GetString("SweeperSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweeper Squares.
        /// </summary>
        internal static string SweeperSquares {
            get {
                return ResourceManager.GetString("SweeperSquares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Leaf Sweeper Game!.
        /// </summary>
        internal static string SweeperWelcome {
            get {
                return ResourceManager.GetString("SweeperWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ten.
        /// </summary>
        internal static string Ten {
            get {
                return ResourceManager.GetString("Ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s a match..
        /// </summary>
        internal static string ThatsMatch {
            get {
                return ResourceManager.GetString("ThatsMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thirteen.
        /// </summary>
        internal static string Thirteen {
            get {
                return ResourceManager.GetString("Thirteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to three.
        /// </summary>
        internal static string Three {
            get {
                return ResourceManager.GetString("Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many apps that ship in Europe are subject to the European standard for digital accessibility, EN 301 549. Many of those standards are based on WCAG..
        /// </summary>
        internal static string TipVisitEN301 {
            get {
                return ResourceManager.GetString("TipVisitEN301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turned up.
        /// </summary>
        internal static string TurnedUp {
            get {
                return ResourceManager.GetString("TurnedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twelve.
        /// </summary>
        internal static string Twelve {
            get {
                return ResourceManager.GetString("Twelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two.
        /// </summary>
        internal static string Two {
            get {
                return ResourceManager.GetString("Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PairsGamePictureDetails file does not contain the expected data. Please review the Pairs Help for more details..
        /// </summary>
        internal static string UnexpectedDataInFile {
            get {
                return ResourceManager.GetString("UnexpectedDataInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmatched cards turned back..
        /// </summary>
        internal static string UnmatchedTurnedBack {
            get {
                return ResourceManager.GetString("UnmatchedTurnedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to up.
        /// </summary>
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.1.1 Non-text Content.
        /// </summary>
        internal static string WCAG111Label {
            get {
                return ResourceManager.GetString("WCAG111Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.1 Text Alternatives.
        /// </summary>
        internal static string WCAG11Label {
            get {
                return ResourceManager.GetString("WCAG11Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.2.1 Audio-only and Video-only (Prerecorded).
        /// </summary>
        internal static string WCAG121Label {
            get {
                return ResourceManager.GetString("WCAG121Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.2.2 Captions (Prerecorded).
        /// </summary>
        internal static string WCAG122Label {
            get {
                return ResourceManager.GetString("WCAG122Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.2.3 Audio Description or Media Alternative (Prerecorded).
        /// </summary>
        internal static string WCAG123Label {
            get {
                return ResourceManager.GetString("WCAG123Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.2.4 Captions (Live).
        /// </summary>
        internal static string WCAG124Label {
            get {
                return ResourceManager.GetString("WCAG124Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.2.5 Audio Description (Prerecorded).
        /// </summary>
        internal static string WCAG125Label {
            get {
                return ResourceManager.GetString("WCAG125Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.2.6 Sign Language (Prerecorded).
        /// </summary>
        internal static string WCAG126Label {
            get {
                return ResourceManager.GetString("WCAG126Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.2.7 Extended Audio Description (Prerecorded).
        /// </summary>
        internal static string WCAG127Label {
            get {
                return ResourceManager.GetString("WCAG127Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.2.8 Media Alternative (Prerecorded).
        /// </summary>
        internal static string WCAG128Label {
            get {
                return ResourceManager.GetString("WCAG128Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.2.9 Audio-only (Live).
        /// </summary>
        internal static string WCAG129Label {
            get {
                return ResourceManager.GetString("WCAG129Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.2 Time-based Media.
        /// </summary>
        internal static string WCAG12Label {
            get {
                return ResourceManager.GetString("WCAG12Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.3.1 Info and Relationships.
        /// </summary>
        internal static string WCAG131Label {
            get {
                return ResourceManager.GetString("WCAG131Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.3.2 Meaningful Sequence.
        /// </summary>
        internal static string WCAG132Label {
            get {
                return ResourceManager.GetString("WCAG132Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.3.3 Sensory Characteristics.
        /// </summary>
        internal static string WCAG133Label {
            get {
                return ResourceManager.GetString("WCAG133Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.3.4 Orientation.
        /// </summary>
        internal static string WCAG134Label {
            get {
                return ResourceManager.GetString("WCAG134Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.3.5 Identify Input Purpose.
        /// </summary>
        internal static string WCAG135Label {
            get {
                return ResourceManager.GetString("WCAG135Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.3.6 Identify Purpose.
        /// </summary>
        internal static string WCAG136Label {
            get {
                return ResourceManager.GetString("WCAG136Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.3 Adaptable.
        /// </summary>
        internal static string WCAG13Label {
            get {
                return ResourceManager.GetString("WCAG13Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.4.10 Reflow.
        /// </summary>
        internal static string WCAG1410Label {
            get {
                return ResourceManager.GetString("WCAG1410Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.4.11 Non-text Contrast.
        /// </summary>
        internal static string WCAG1411Label {
            get {
                return ResourceManager.GetString("WCAG1411Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.4.12 Text Spacing.
        /// </summary>
        internal static string WCAG1412Label {
            get {
                return ResourceManager.GetString("WCAG1412Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.4.13 Content on Hover or Focus.
        /// </summary>
        internal static string WCAG1413Label {
            get {
                return ResourceManager.GetString("WCAG1413Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.4.1 Use of Color.
        /// </summary>
        internal static string WCAG141Label {
            get {
                return ResourceManager.GetString("WCAG141Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.4.2 Audio Control.
        /// </summary>
        internal static string WCAG142Label {
            get {
                return ResourceManager.GetString("WCAG142Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.4.3 Contrast (Minimum).
        /// </summary>
        internal static string WCAG143Label {
            get {
                return ResourceManager.GetString("WCAG143Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.4.4 Resize text.
        /// </summary>
        internal static string WCAG144Label {
            get {
                return ResourceManager.GetString("WCAG144Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.4.5 Images of Text.
        /// </summary>
        internal static string WCAG145Label {
            get {
                return ResourceManager.GetString("WCAG145Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.4.6 Contrast (Enhanced).
        /// </summary>
        internal static string WCAG146Label {
            get {
                return ResourceManager.GetString("WCAG146Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.4.7 Low or No Background Audio.
        /// </summary>
        internal static string WCAG147Label {
            get {
                return ResourceManager.GetString("WCAG147Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.4.8 Visual Presentation.
        /// </summary>
        internal static string WCAG148Label {
            get {
                return ResourceManager.GetString("WCAG148Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.4.9 Images of Text (No Exception).
        /// </summary>
        internal static string WCAG149Label {
            get {
                return ResourceManager.GetString("WCAG149Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.4 Distinguishable.
        /// </summary>
        internal static string WCAG14Label {
            get {
                return ResourceManager.GetString("WCAG14Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Perceivable.
        /// </summary>
        internal static string WCAG1Label {
            get {
                return ResourceManager.GetString("WCAG1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.1.1 Keyboard.
        /// </summary>
        internal static string WCAG211Label {
            get {
                return ResourceManager.GetString("WCAG211Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.1.2 No Keyboard Trap.
        /// </summary>
        internal static string WCAG212Label {
            get {
                return ResourceManager.GetString("WCAG212Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.1.3 Keyboard (No Exception).
        /// </summary>
        internal static string WCAG213Label {
            get {
                return ResourceManager.GetString("WCAG213Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.1.4 Character Key Shortcuts.
        /// </summary>
        internal static string WCAG214Label {
            get {
                return ResourceManager.GetString("WCAG214Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.1 Keyboard Accessible.
        /// </summary>
        internal static string WCAG21Label {
            get {
                return ResourceManager.GetString("WCAG21Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.2.1 Timing Adjustable.
        /// </summary>
        internal static string WCAG221Label {
            get {
                return ResourceManager.GetString("WCAG221Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.2.2 Pause, Stop, Hide.
        /// </summary>
        internal static string WCAG222Label {
            get {
                return ResourceManager.GetString("WCAG222Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.2.3 No Timing.
        /// </summary>
        internal static string WCAG223Label {
            get {
                return ResourceManager.GetString("WCAG223Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.2.4 Interruptions.
        /// </summary>
        internal static string WCAG224Label {
            get {
                return ResourceManager.GetString("WCAG224Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.2.5 Re-authenticating.
        /// </summary>
        internal static string WCAG225Label {
            get {
                return ResourceManager.GetString("WCAG225Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.2.6 Timeouts.
        /// </summary>
        internal static string WCAG226Label {
            get {
                return ResourceManager.GetString("WCAG226Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.2 Enough Time.
        /// </summary>
        internal static string WCAG22Label {
            get {
                return ResourceManager.GetString("WCAG22Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.3.1 Three Flashes or Below Threshold.
        /// </summary>
        internal static string WCAG231Label {
            get {
                return ResourceManager.GetString("WCAG231Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.3.2 Three Flashes.
        /// </summary>
        internal static string WCAG232Label {
            get {
                return ResourceManager.GetString("WCAG232Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.3.3 Animation from Interactions.
        /// </summary>
        internal static string WCAG233Label {
            get {
                return ResourceManager.GetString("WCAG233Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.3 Seizures and Physical Reactions.
        /// </summary>
        internal static string WCAG23Label {
            get {
                return ResourceManager.GetString("WCAG23Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.4.10 Section Headings.
        /// </summary>
        internal static string WCAG2410Label {
            get {
                return ResourceManager.GetString("WCAG2410Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.4.11 Focus Appearance (Minimum).
        /// </summary>
        internal static string WCAG2411Label {
            get {
                return ResourceManager.GetString("WCAG2411Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.4.12 Focus Appearance (Enhanced).
        /// </summary>
        internal static string WCAG2412Label {
            get {
                return ResourceManager.GetString("WCAG2412Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.4.13 Page Break Navigation.
        /// </summary>
        internal static string WCAG2413Label {
            get {
                return ResourceManager.GetString("WCAG2413Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.4.1 Bypass Blocks.
        /// </summary>
        internal static string WCAG241Label {
            get {
                return ResourceManager.GetString("WCAG241Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.4.2 Page Titled.
        /// </summary>
        internal static string WCAG242Label {
            get {
                return ResourceManager.GetString("WCAG242Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.4.3 Focus Order.
        /// </summary>
        internal static string WCAG243Label {
            get {
                return ResourceManager.GetString("WCAG243Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.4.4 Link Purpose (In Context).
        /// </summary>
        internal static string WCAG244Label {
            get {
                return ResourceManager.GetString("WCAG244Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.4.5 Multiple Ways.
        /// </summary>
        internal static string WCAG245Label {
            get {
                return ResourceManager.GetString("WCAG245Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.4.6 Headings and Labels.
        /// </summary>
        internal static string WCAG246Label {
            get {
                return ResourceManager.GetString("WCAG246Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.4.7 Focus Visible.
        /// </summary>
        internal static string WCAG247Label {
            get {
                return ResourceManager.GetString("WCAG247Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.4.8 Location.
        /// </summary>
        internal static string WCAG248Label {
            get {
                return ResourceManager.GetString("WCAG248Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.4.9 Link Purpose (Link Only).
        /// </summary>
        internal static string WCAG249Label {
            get {
                return ResourceManager.GetString("WCAG249Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.4 Navigable.
        /// </summary>
        internal static string WCAG24Label {
            get {
                return ResourceManager.GetString("WCAG24Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.5.1 Pointer Gestures.
        /// </summary>
        internal static string WCAG251Label {
            get {
                return ResourceManager.GetString("WCAG251Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.5.2 Pointer Cancellation.
        /// </summary>
        internal static string WCAG252Label {
            get {
                return ResourceManager.GetString("WCAG252Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.5.3 Label in Name.
        /// </summary>
        internal static string WCAG253Label {
            get {
                return ResourceManager.GetString("WCAG253Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.5.4 Motion Actuation.
        /// </summary>
        internal static string WCAG254Label {
            get {
                return ResourceManager.GetString("WCAG254Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.5.5 Target Size (Enhanced).
        /// </summary>
        internal static string WCAG255Label {
            get {
                return ResourceManager.GetString("WCAG255Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.5.6 Concurrent Input Mechanisms.
        /// </summary>
        internal static string WCAG256Label {
            get {
                return ResourceManager.GetString("WCAG256Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.5.7 Dragging Movements.
        /// </summary>
        internal static string WCAG257Label {
            get {
                return ResourceManager.GetString("WCAG257Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.5.8 Target Size (Minimum).
        /// </summary>
        internal static string WCAG258Label {
            get {
                return ResourceManager.GetString("WCAG258Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.5 Input Modalities.
        /// </summary>
        internal static string WCAG25Label {
            get {
                return ResourceManager.GetString("WCAG25Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Operable.
        /// </summary>
        internal static string WCAG2Label {
            get {
                return ResourceManager.GetString("WCAG2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.1.1 Language of Page.
        /// </summary>
        internal static string WCAG311Label {
            get {
                return ResourceManager.GetString("WCAG311Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.1.2 Language of Parts.
        /// </summary>
        internal static string WCAG312Label {
            get {
                return ResourceManager.GetString("WCAG312Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.1.3 Unusual Words.
        /// </summary>
        internal static string WCAG313Label {
            get {
                return ResourceManager.GetString("WCAG313Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.1.4 Abbreviations.
        /// </summary>
        internal static string WCAG314Label {
            get {
                return ResourceManager.GetString("WCAG314Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.1.5 Reading Level.
        /// </summary>
        internal static string WCAG315Label {
            get {
                return ResourceManager.GetString("WCAG315Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.1.6 Pronunciation.
        /// </summary>
        internal static string WCAG316Label {
            get {
                return ResourceManager.GetString("WCAG316Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.1 Readable.
        /// </summary>
        internal static string WCAG31Label {
            get {
                return ResourceManager.GetString("WCAG31Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.2.1 On Focus.
        /// </summary>
        internal static string WCAG321Label {
            get {
                return ResourceManager.GetString("WCAG321Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.2.2 On Input.
        /// </summary>
        internal static string WCAG322Label {
            get {
                return ResourceManager.GetString("WCAG322Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.2.3 Consistent Navigation.
        /// </summary>
        internal static string WCAG323Label {
            get {
                return ResourceManager.GetString("WCAG323Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.2.4 Consistent Identification.
        /// </summary>
        internal static string WCAG324Label {
            get {
                return ResourceManager.GetString("WCAG324Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.2.5 Change on Request.
        /// </summary>
        internal static string WCAG325Label {
            get {
                return ResourceManager.GetString("WCAG325Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.2.6 Consistent Help.
        /// </summary>
        internal static string WCAG326Label {
            get {
                return ResourceManager.GetString("WCAG326Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.2.7 Visible Controls.
        /// </summary>
        internal static string WCAG327Label {
            get {
                return ResourceManager.GetString("WCAG327Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.2 Predictable.
        /// </summary>
        internal static string WCAG32Label {
            get {
                return ResourceManager.GetString("WCAG32Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.3.1 Error Identification.
        /// </summary>
        internal static string WCAG331Label {
            get {
                return ResourceManager.GetString("WCAG331Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.3.2 Labels or Instructions.
        /// </summary>
        internal static string WCAG332Label {
            get {
                return ResourceManager.GetString("WCAG332Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.3.3 Error Suggestion.
        /// </summary>
        internal static string WCAG333Label {
            get {
                return ResourceManager.GetString("WCAG333Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.3.4 Error Prevention (Legal, Financial, Data).
        /// </summary>
        internal static string WCAG334Label {
            get {
                return ResourceManager.GetString("WCAG334Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.3.5 Help.
        /// </summary>
        internal static string WCAG335Label {
            get {
                return ResourceManager.GetString("WCAG335Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.3.6 Error Prevention (All).
        /// </summary>
        internal static string WCAG336Label {
            get {
                return ResourceManager.GetString("WCAG336Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.3.7 Accessible Authentication.
        /// </summary>
        internal static string WCAG337Label {
            get {
                return ResourceManager.GetString("WCAG337Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.3.8 Redundant entry.
        /// </summary>
        internal static string WCAG338Label {
            get {
                return ResourceManager.GetString("WCAG338Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.3 Input Assistance.
        /// </summary>
        internal static string WCAG33Label {
            get {
                return ResourceManager.GetString("WCAG33Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Understandable.
        /// </summary>
        internal static string WCAG3Label {
            get {
                return ResourceManager.GetString("WCAG3Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.1.1 Parsing.
        /// </summary>
        internal static string WCAG411Label {
            get {
                return ResourceManager.GetString("WCAG411Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.1.2 Name, Role, Value.
        /// </summary>
        internal static string WCAG412Label {
            get {
                return ResourceManager.GetString("WCAG412Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.1.3 Status Messages.
        /// </summary>
        internal static string WCAG413Label {
            get {
                return ResourceManager.GetString("WCAG413Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.1 Compatible.
        /// </summary>
        internal static string WCAG41Label {
            get {
                return ResourceManager.GetString("WCAG41Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Robust.
        /// </summary>
        internal static string WCAG4Label {
            get {
                return ResourceManager.GetString("WCAG4Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After closing this message, please review the help content for details on how to play this game.
        ///
        ///The help content can be reached via the menu button at the top left corner of the app. Screen readers may announce this button as the &quot;Open Navigation&quot; button or &quot;Menu&quot; button. When the menu button is clicked, a menu of items is shown beneath it. The items can be used to switch between the games, or to restart a game, or to have the help content shown..
        /// </summary>
        internal static string WelcomeInstructions {
            get {
                return ResourceManager.GetString("WelcomeInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where&apos;s WCAG?.
        /// </summary>
        internal static string Wheres {
            get {
                return ResourceManager.GetString("Wheres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default, the bonus questions are from a fixed set of questions that come with the Where&apos;s WCAG? game. But if you&apos;d prefer, you can select your own set of questions for players to answer. Select your own set of questions with the &quot;Select Questions&quot; button below. The text file you select must contain fifteen question and answer pairs. Each question lies on its own line in the file, and starts with &quot;Q:&quot;. Each answer lies on the line that follows the associated question, and starts with &quot;A:&quot;. An answer is a  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WheresBonusQuestionsInstructions {
            get {
                return ResourceManager.GetString("WheresBonusQuestionsInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After every correct answer in the Where&apos;s WCAG game, have a bonus WCAG-related question asked..
        /// </summary>
        internal static string WheresBonusQuestionsIntro {
            get {
                return ResourceManager.GetString("WheresBonusQuestionsIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions from the default set of questions will be presented in a random order. Questions loaded from your own set of custom questions will be presented in the order that they were loaded from the questions file..
        /// </summary>
        internal static string WheresBonusQuestionsOrder {
            get {
                return ResourceManager.GetString("WheresBonusQuestionsOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sample bonus question file is available at https://github.com/gbarkerz/GridGames/blob/master/GridGames/SampleWheresWCAGBonusQuestions.txt. Consider copying the contents of that file into your own Q&amp;A file, and then changing the Q&amp;A pairs to suit your own purposes..
        /// </summary>
        internal static string WheresBonusQuestionsViewSample {
            get {
                return ResourceManager.GetString("WheresBonusQuestionsViewSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where&apos;s WCAG? Help.
        /// </summary>
        internal static string WheresGameHelp {
            get {
                return ResourceManager.GetString("WheresGameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where&apos;s WCAG? Settings.
        /// </summary>
        internal static string WheresSettings {
            get {
                return ResourceManager.GetString("WheresSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Where&apos;s WCAG? Game!.
        /// </summary>
        internal static string WheresWelcome {
            get {
                return ResourceManager.GetString("WheresWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won the game in {0} goes.
        ///
        ///Would you like to play another game?.
        /// </summary>
        internal static string WonInMoves {
            get {
                return ResourceManager.GetString("WonInMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won the game in {0} goes, and got {1} bonus questions correct!
        ///
        ///Would you like to play another game?.
        /// </summary>
        internal static string WonInMovesWithBonusQuestionCount {
            get {
                return ResourceManager.GetString("WonInMovesWithBonusQuestionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
